// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiShow.Data.Models;

#nullable enable
public partial class Animal : BaseEntity
{
    public string? AnimalName { get; set; }

    public int? VarietyId { get; set; }

    public int? Size { get; set; }

    public DateTime? BirthDate { get; set; }

    public string? ImgLink { get; set; }

    public int? OwnerId { get; set; }

    public int? Weight { get; set; }

    public string? Description { get; set; }

    public string? HeathStatus { get; set; }

    public int? Gender { get; set; }

    [ForeignKey(nameof(OwnerId))]
    public virtual Account? Owner { get; set; }

    public virtual ICollection<RegisterForm>? RegisterForms { get; set; } = new List<RegisterForm>();

    [ForeignKey(nameof(VarietyId))]
    public virtual Variety? Variety { get; set; }
}