// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;

namespace KoiShow.Data.Models;

#nullable enable
public partial class Contest : BaseEntity
{
    public string? ContestName { get; set; }

    public string? Title { get; set; }

    public string? Description { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string? Location { get; set; }

    public string? CompetitionType { get; set; }

    public int? Status { get; set; }

    public int? Participants { get; set; }

    public string? Image { get; set; }

    public string? ContactInfo { get; set; }

    public int? ShapePointPercent { get; set; }

    public int? ColorPointPercent { get; set; }

    public int? PatternPointPercent { get; set; }

    public virtual ICollection<ContestResult>? ContestResults { get; set; } = new List<ContestResult>();

    public virtual ICollection<RegisterForm>? RegisterForms { get; set; } = new List<RegisterForm>();
}