// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiShow.Data.Models;

#nullable enable
public partial class ContestResult : BaseEntity
{
    public int? ContestId { get; set; }

    public string? ContestResultName { get; set; }

    public string? WinnerName { get; set; }

    public string? ContestResultDescription { get; set; }

    public double? TotalScore { get; set; }

    public int? Rank { get; set; }

    public string? Comments { get; set; }

    public bool? IsPublished { get; set; }

    public string? Category { get; set; }

    public int? Prize { get; set; }

    public string? PrizeDescription { get; set; }

    [ForeignKey(nameof(ContestId))]
    public virtual Contest? Contest { get; set; }
}