// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiShow.Data.Models;

#nullable enable
public partial class New : BaseEntity
{
    public string? Title { get; set; }

    public string? Description { get; set; }

    public string? HtmlContent { get; set; }

    public string? Category { get; set; }

    public string? Tags { get; set; }

    public string? IsPublished { get; set; }

    public DateTime? PublishDate { get; set; }

    public string? FeaturedImage { get; set; }

    public int? ViewCount { get; set; }

    public int? AuthorId { get; set; }

    [ForeignKey(nameof(AuthorId))]
    public virtual Account? Author { get; set; }
}