// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiShow.Data.Models;

#nullable enable
public partial class Point : BaseEntity
{
    public int? ShapePoint { get; set; }

    public int? ColorPoint { get; set; }

    public int? PatternPoint { get; set; }

    public string? Comment { get; set; }

    public int? JuryId { get; set; }

    public int? RegisterFormId { get; set; }

    public int? PointStatus { get; set; }

    public string? JudgeRank { get; set; }

    public int? Penalties { get; set; }

    public int? TotalScore { get; set; }

    [ForeignKey(nameof(JuryId))]
    public virtual Account? Jury { get; set; }

    [ForeignKey(nameof(RegisterFormId))]
    public virtual RegisterForm? RegisterForm { get; set; }
}