// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace KoiShow.Data.Models;

#nullable enable
public partial class RegisterForm : BaseEntity
{
    public int? ContestId { get; set; }

    public int? AnimalId { get; set; }

    public string? EntryTitle { get; set; }

    public string? CheckinStatus { get; set; }

    public DateTime? RegistrationDate { get; set; }

    public string? ApprovalStatus { get; set; }

    public string? Notes { get; set; }

    public string? Status { get; set; }

    public string? Image { get; set; }

    public string? HealthStatus { get; set; }

    public string? Color { get; set; }

    public string? Shape { get; set; }

    public string? Pattern { get; set; }

    [ForeignKey(nameof(AnimalId))]
    public virtual Animal? Animal { get; set; }

    [ForeignKey(nameof(ContestId))]
    public virtual Contest? Contest { get; set; }

    public virtual ICollection<Payment>? Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Point>? Points { get; set; } = new List<Point>();
}