// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using KoiShow.Data.Base;
using System;
using System.Collections.Generic;

namespace KoiShow.Data.Models;

public partial class Variety : BaseEntity
{
    public string Description { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}